name: surrealdb_dart
description: SurrealDB Dart client library
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-279.0.dev

# Add regular dependencies here.
dependencies:
  dio: ^5.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
